export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";

export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";

export const SET_LISTING_DATA = "SET_LISTING_DATA";
export const SET_CATEGORY_DATA = "SET_CATEGORY_DATA";

const types = {
  GET_CHAT_ROOMS_SUCCESS: "GET_CHAT_ROOMS_SUCCESS",
  GET_CHAT_ROOMS_ERROR: "GET_CHAT_ROOMS_ERROR",
  GET_CHAT_MESSAGE_SUCCESS: "GET_CHAT_MESSAGE_SUCCESS",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  SET_UNREAD_MESSAGE_COUNT: "SET_UNREAD_MESSAGE_COUNT",
  GET_GROUP_CHAT_ROOMS: "GET_GROUP_CHAT_ROOMS",
};

export const staffTypes = {
  GET_ACTIVITY_LISTS: "GET_ACTIVITY_LISTS",
  STAFF_LISTS: "STAFF_LISTS",
};
export default types;
